### ISSUE TITLE
Doesn't compile 

### ISSUE THREAD

**Issue by Lightn1ng** [ashyx/kernel_gts28ve-gts210ve#2]
I do

./ashyx_build_t713_kernel.sh

And this happens

arch/arm64/configs/selinux_defconfig:7:warning: override: reassigning to symbol SECURITY
arch/arm64/configs/selinux_defconfig:8:warning: override: reassigning to symbol LSM_MMAP_MIN_ADDR
arch/arm64/configs/selinux_defconfig:9:warning: override: reassigning to symbol SECURITY_NETWORK
arch/arm64/configs/selinux_defconfig:10:warning: override: reassigning to symbol SECURITY_SELINUX
arch/arm64/configs/selinux_defconfig:13:warning: symbol value 'y' invalid for SECURITY_SELINUX_CHECKREQPROT_VALUE
arch/arm64/configs/selinux_defconfig:15:warning: override: reassigning to symbol NF_CONNTRACK_SECMARK
arch/arm64/configs/selinux_defconfig:16:warning: override: reassigning to symbol NETFILTER_XT_TARGET_CONNSECMARK
arch/arm64/configs/selinux_defconfig:18:warning: override: reassigning to symbol IP_NF_SECURITY
KCONFIG_LOG_SELINUX(arch/arm64/configs/selinux_log_defconfig)
KCONFIG_TIMA((null))
KCONFIG_DMVERITY((null))
KCONFIG_VARIANT(arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig)
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:23:warning: override: reassigning to symbol USB_HOST_NOTIFY
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:92:warning: override: reassigning to symbol SECURE_TOUCH
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:117:warning: override: reassigning to symbol SENSORS
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:140:warning: override: reassigning to symbol MSM_BT_POWER
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:152:warning: override: reassigning to symbol INPUT_GPIO
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:166:warning: override: reassigning to symbol ZSMALLOC
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:182:warning: override: reassigning to symbol CNSS_SDIO
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:183:warning: override: reassigning to symbol CLD_HL_SDIO_CORE
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:186:warning: override: reassigning to symbol WCNSS_MEM_PRE_ALLOC
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:187:warning: override: reassigning to symbol WCNSS_CORE
KCONFIG_DEBUG((null))
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
#
# configuration written to .config
#
Makefile:809: *** multiple target patterns.  Stop.
DTB combiner:
  Input directory: 'arch/arm/boot/dts/'
  Output file: 'arch/arm64/boot/dt.img'
Found file: msm8976-sec-gts28vewifi-eur-r00.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8976-sec-gts28vewifi-eur-r05.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8976-sec-gts28vewifi-eur-r01.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8976-sec-gts28vewifi-eur-r04.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
=> Found 0 unique DTB(s)

Am I just being incredibly stupid?

**Comment by ashyx** [comment]
Where have you put your path to the tool chain? 
It must be in ashyx_build_t713_kernel.sh and nowhere else.

**Comment by Lightn1ng** [comment]
Now I shall google what's a toolchain

which one should I use and how do I install it? thanks.

**Comment by Lightn1ng** [comment]
I've gotten the toolchain from the android-ndk v4.9 and exported it - now I'm getting another error:



arch/arm64/configs/msm8976_sec_defconfig:453:warning: override: reassigning to symbol HID_MULTITOUCH
arch/arm64/configs/msm8976_sec_defconfig:478:warning: override: reassigning to symbol HID_MULTITOUCH
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
KCONFIG_SELINUX(arch/arm64/configs/selinux_defconfig)
arch/arm64/configs/selinux_defconfig:1:warning: override: reassigning to symbol EXT2_FS_XATTR
arch/arm64/configs/selinux_defconfig:4:warning: override: reassigning to symbol EXT4_FS_SECURITY
arch/arm64/configs/selinux_defconfig:5:warning: override: reassigning to symbol AUDIT
arch/arm64/configs/selinux_defconfig:7:warning: override: reassigning to symbol SECURITY
arch/arm64/configs/selinux_defconfig:8:warning: override: reassigning to symbol LSM_MMAP_MIN_ADDR
arch/arm64/configs/selinux_defconfig:9:warning: override: reassigning to symbol SECURITY_NETWORK
arch/arm64/configs/selinux_defconfig:10:warning: override: reassigning to symbol SECURITY_SELINUX
arch/arm64/configs/selinux_defconfig:13:warning: symbol value 'y' invalid for SECURITY_SELINUX_CHECKREQPROT_VALUE
arch/arm64/configs/selinux_defconfig:15:warning: override: reassigning to symbol NF_CONNTRACK_SECMARK
arch/arm64/configs/selinux_defconfig:16:warning: override: reassigning to symbol NETFILTER_XT_TARGET_CONNSECMARK
arch/arm64/configs/selinux_defconfig:18:warning: override: reassigning to symbol IP_NF_SECURITY
KCONFIG_LOG_SELINUX(arch/arm64/configs/selinux_log_defconfig)
KCONFIG_TIMA((null))
KCONFIG_DMVERITY((null))
KCONFIG_VARIANT(arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig)
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:23:warning: override: reassigning to symbol USB_HOST_NOTIFY
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:92:warning: override: reassigning to symbol SECURE_TOUCH
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:117:warning: override: reassigning to symbol SENSORS
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:140:warning: override: reassigning to symbol MSM_BT_POWER
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:152:warning: override: reassigning to symbol INPUT_GPIO
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:166:warning: override: reassigning to symbol ZSMALLOC
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:182:warning: override: reassigning to symbol CNSS_SDIO
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:183:warning: override: reassigning to symbol CLD_HL_SDIO_CORE
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:186:warning: override: reassigning to symbol WCNSS_MEM_PRE_ALLOC
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:187:warning: override: reassigning to symbol WCNSS_CORE
KCONFIG_DEBUG((null))
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
#
# configuration written to .config
#
Makefile:809: *** multiple target patterns.  Stop.
DTB combiner:
  Input directory: 'arch/arm/boot/dts/'
  Output file: 'arch/arm64/boot/dt.img'
Found file: msm8976-sec-gts28vewifi-eur-r00.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8976-sec-gts28vewifi-eur-r05.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8976-sec-gts28vewifi-eur-r01.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8976-sec-gts28vewifi-eur-r04.dtb ...
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
=> Found 0 unique DTB(s)
ryan@potato:~/cm13/kernel/samsung/gts28vewifi$ export CROSS_COMPILE=/home/ryan/cm13/kernel/samsung/gts28vewifi/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-
ryan@potato:~/cm13/kernel/samsung/gts28vewifi$ nano ashyx_build_t713_kernel.sh
ryan@potato:~/cm13/kernel/samsung/gts28vewifi$ ./ashyx_build_t713_kernel.sh
arch/arm64/configs/msm8976_sec_defconfig:453:warning: override: reassigning to symbol HID_MULTITOUCH
arch/arm64/configs/msm8976_sec_defconfig:478:warning: override: reassigning to symbol HID_MULTITOUCH
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
KCONFIG_SELINUX(arch/arm64/configs/selinux_defconfig)
arch/arm64/configs/selinux_defconfig:1:warning: override: reassigning to symbol EXT2_FS_XATTR
arch/arm64/configs/selinux_defconfig:4:warning: override: reassigning to symbol EXT4_FS_SECURITY
arch/arm64/configs/selinux_defconfig:5:warning: override: reassigning to symbol AUDIT
arch/arm64/configs/selinux_defconfig:7:warning: override: reassigning to symbol SECURITY
arch/arm64/configs/selinux_defconfig:8:warning: override: reassigning to symbol LSM_MMAP_MIN_ADDR
arch/arm64/configs/selinux_defconfig:9:warning: override: reassigning to symbol SECURITY_NETWORK
arch/arm64/configs/selinux_defconfig:10:warning: override: reassigning to symbol SECURITY_SELINUX
arch/arm64/configs/selinux_defconfig:13:warning: symbol value 'y' invalid for SECURITY_SELINUX_CHECKREQPROT_VALUE
arch/arm64/configs/selinux_defconfig:15:warning: override: reassigning to symbol NF_CONNTRACK_SECMARK
arch/arm64/configs/selinux_defconfig:16:warning: override: reassigning to symbol NETFILTER_XT_TARGET_CONNSECMARK
arch/arm64/configs/selinux_defconfig:18:warning: override: reassigning to symbol IP_NF_SECURITY
KCONFIG_LOG_SELINUX(arch/arm64/configs/selinux_log_defconfig)
KCONFIG_TIMA((null))
KCONFIG_DMVERITY((null))
KCONFIG_VARIANT(arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig)
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:23:warning: override: reassigning to symbol USB_HOST_NOTIFY
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:92:warning: override: reassigning to symbol SECURE_TOUCH
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:117:warning: override: reassigning to symbol SENSORS
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:140:warning: override: reassigning to symbol MSM_BT_POWER
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:152:warning: override: reassigning to symbol INPUT_GPIO
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:166:warning: override: reassigning to symbol ZSMALLOC
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:182:warning: override: reassigning to symbol CNSS_SDIO
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:183:warning: override: reassigning to symbol CLD_HL_SDIO_CORE
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:186:warning: override: reassigning to symbol WCNSS_MEM_PRE_ALLOC
arch/arm64/configs/msm8976_sec_gts28vewifi_eur_defconfig:187:warning: override: reassigning to symbol WCNSS_CORE
KCONFIG_DEBUG((null))
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
#
# configuration written to .config
#
scripts/kconfig/conf --silentoldconfig Kconfig
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
warning: (SND_SOC_APQ8084 && SND_SOC_MSM8X16 && SND_SOC_MSM8994) selects SND_SOC_CPE which has unmet direct dependencies (SOUND && !M68K && !UML && SND && SND_SOC && SND_SOC_WCD_CPE)
warning: (ARCH_MSM) selects DEVFREQ_GOV_MSM_BW_HWMON which has unmet direct dependencies (PM_DEVFREQ && (ARCH_MSM_KRAIT || ARCH_MSM_BIMC_BWMON))
Makefile:606: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler
  WRAP    arch/arm64/include/generated/asm/checksum.h
  WRAP    arch/arm64/include/generated/asm/bugs.h
  WRAP    arch/arm64/include/generated/asm/clkdev.h
  WRAP    arch/arm64/include/generated/asm/cputime.h
  WRAP    arch/arm64/include/generated/asm/current.h
  WRAP    arch/arm64/include/generated/asm/delay.h
  WRAP    arch/arm64/include/generated/asm/div64.h
  WRAP    arch/arm64/include/generated/asm/dma.h
  WRAP    arch/arm64/include/generated/asm/emergency-restart.h
  WRAP    arch/arm64/include/generated/asm/early_ioremap.h
  WRAP    arch/arm64/include/generated/asm/errno.h
  WRAP    arch/arm64/include/generated/asm/ftrace.h
  WRAP    arch/arm64/include/generated/asm/hw_irq.h
  WRAP    arch/arm64/include/generated/asm/ioctl.h
  WRAP    arch/arm64/include/generated/asm/ioctls.h
  WRAP    arch/arm64/include/generated/asm/ipcbuf.h
  WRAP    arch/arm64/include/generated/asm/irq_regs.h
  WRAP    arch/arm64/include/generated/asm/kdebug.h
  WRAP    arch/arm64/include/generated/asm/kmap_types.h
  WRAP    arch/arm64/include/generated/asm/kvm_para.h
  WRAP    arch/arm64/include/generated/asm/local.h
  WRAP    arch/arm64/include/generated/asm/local64.h
  WRAP    arch/arm64/include/generated/asm/mcs_spinlock.h
  WRAP    arch/arm64/include/generated/asm/mman.h
  WRAP    arch/arm64/include/generated/asm/msgbuf.h
  WRAP    arch/arm64/include/generated/asm/mutex.h
  WRAP    arch/arm64/include/generated/asm/pci.h
  WRAP    arch/arm64/include/generated/asm/poll.h
  WRAP    arch/arm64/include/generated/asm/resource.h
  WRAP    arch/arm64/include/generated/asm/rwsem.h
  WRAP    arch/arm64/include/generated/asm/scatterlist.h
  WRAP    arch/arm64/include/generated/asm/sections.h
  WRAP    arch/arm64/include/generated/asm/segment.h
  WRAP    arch/arm64/include/generated/asm/sembuf.h
  WRAP    arch/arm64/include/generated/asm/serial.h
  WRAP    arch/arm64/include/generated/asm/simd.h
  WRAP    arch/arm64/include/generated/asm/shmbuf.h
  WRAP    arch/arm64/include/generated/asm/sizes.h
  WRAP    arch/arm64/include/generated/asm/socket.h
  WRAP    arch/arm64/include/generated/asm/sockios.h
  WRAP    arch/arm64/include/generated/asm/swab.h
  WRAP    arch/arm64/include/generated/asm/switch_to.h
  WRAP    arch/arm64/include/generated/asm/termbits.h
  WRAP    arch/arm64/include/generated/asm/termios.h
  WRAP    arch/arm64/include/generated/asm/trace_clock.h
  CHK     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/asm/topology.h
  WRAP    arch/arm64/include/generated/asm/types.h
  UPD     include/generated/uapi/linux/version.h
  WRAP    arch/arm64/include/generated/asm/unaligned.h
  WRAP    arch/arm64/include/generated/asm/user.h
  WRAP    arch/arm64/include/generated/asm/vga.h
  WRAP    arch/arm64/include/generated/asm/xor.h
  WRAP    arch/arm64/include/generated/uapi/asm/kvm_para.h
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/data.o
  SHIPPED scripts/dtc/dtc-lexer.lex.c
  SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/genksyms/genksyms.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/util.o
  SHIPPED scripts/genksyms/lex.lex.c
  SHIPPED scripts/genksyms/keywords.hash.c
  SHIPPED scripts/genksyms/parse.tab.h
  SHIPPED scripts/genksyms/parse.tab.c
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/genksyms/genksyms
  CC      scripts/mod/empty.o
  HOSTLD  scripts/dtc/dtc
arm-linux-androideabi-gcc: error: unrecognized command line option '-mgeneral-regs-only'
scripts/Makefile.build:308: recipe for target 'scripts/mod/empty.o' failed
make[2]: *** [scripts/mod/empty.o] Error 1
scripts/Makefile.build:455: recipe for target 'scripts/mod' failed
make[1]: *** [scripts/mod] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:525: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: *** Waiting for unfinished jobs....
DTB combiner:
  Input directory: 'arch/arm/boot/dts/'
  Output file: 'arch/arm64/boot/dt.img'
Found file: msm8976-sec-gts28vewifi-eur-r00.dtb ...
Version:2
chipset: 278, rev: 65537, platform: 8, subtype: 0, pmic0: 0, pmic1: 0, pmic2: 0, pmic3: 0
Found file: msm8976-sec-gts28vewifi-eur-r05.dtb ...
Version:2
chipset: 278, rev: 65537, platform: 8, subtype: 5, pmic0: 0, pmic1: 0, pmic2: 0, pmic3: 0
Found file: msm8976-sec-gts28vewifi-eur-r01.dtb ...
Version:2
chipset: 278, rev: 65537, platform: 8, subtype: 1, pmic0: 0, pmic1: 0, pmic2: 0, pmic3: 0
Found file: msm8976-sec-gts28vewifi-eur-r04.dtb ...
Version:2
chipset: 278, rev: 65537, platform: 8, subtype: 4, pmic0: 0, pmic1: 0, pmic2: 0, pmic3: 0
=> Found 4 unique DTB(s)

Generating master DTB... completed
ryan@potato:~/cm13/kernel/samsung/gts28vewifi$

**Comment by Lightn1ng** [comment]
Turns out I was just being stupid.

I was using an ARM toolchain to compile an ARM64 kernel.
