### ISSUE TITLE
Where does the output go?

### ISSUE THREAD

**Issue by Lightn1ng** [ashyx/kernel_gts28ve-gts210ve#3]
After running the build script, there is no boot.img. Is there something I need to do to pack everything together? Thanks.

**Comment by ashyx** [comment]
The compiler will tell you the path to the kernel image.  Arch/arm64/boot
You need to repack the kernel with the stock ramdisk.

**Comment by Lightn1ng** [comment]
Thanks, I will look on google for how to repack the kernel and the ramdisk.

But magically I'm getting another error. I posted it in the XDA thread.
